baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Okkur - Syna"
theme = "syna"
themesDir = "themes"
enableGitInfo = true
version = "0.17.4"
disableKinds = [ "RSS", "taxonomy", "taxonomyTerm" ]
ignorefiles = [ "content/dev/.*" ]
googleAnalytics = ""
baseURL = ""
publishDir = "public"

[outputs]
home = [ "HTML", "JSON" ]

[frontmatter]
date = [ "date", "lastmod" ]
lastmod = [ "lastmod", ":git", "date" ]

[markup.goldmark.renderer]
unsafe = true

[params]
name = "Okkur Labs"
description = "Open Source Theme for your next project"
debug = true
unsafeEvents = true
style = { }

  [params.custom]
  favicon = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  favicon_png = "favicon.png"
  favicon_svg = "favicon.svg"

  [params.analytics]
  piwik = { }

  [params.fontawesome]
  disabled = false
  pro = false

  [params.colors]
  primary = "#00838F"
  secondary = "#868e96"
  success = "#008f54"
  info = "#00c9dc"
  warning = "#fdf314"
  danger = "#dc1200"
  light = "#f8f9fa"
  dark = "#343a40"

[[menu.main]]
url = "/"
name = "Home"
weight = 10

[[menu.main]]
url = "/fragments"
name = "Fragments"
weight = 20

[[menu.main]]
url = "/docs"
name = "Docs"
weight = 30

[[menu.main]]
url = "/about"
name = "About"
weight = 40

[[menu.footer]]
url = "https://syna.okkur.org/demo"
name = "Getting Started"
weight = 10

[[menu.footer]]
url = "https://about.okkur.org/"
name = "About Okkur Labs"
weight = 20

[[menu.footer_social]]
weight = 30
name = "github"
url = "https://git.okkur.org/syna"
pre = "fab fa-github fa-stack-2x"

[[menu.copyright_footer]]
url = "/about"
name = "About Us"
weight = 10
